steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA
      - .               # build context is the repo root

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --update-secrets=DATABASE_URL=DATABASE_URL:latest,NEON_AUTH_BASE_URL=NEON_AUTH_BASE_URL:latest,FLASK_SECRET_KEY=FLASK_SECRET_KEY:latest,GOOGLE_SERVICE_ACCOUNT_EMAIL=GOOGLE_SERVICE_ACCOUNT_EMAIL:latest,GOOGLE_PRIVATE_KEY=GOOGLE_PRIVATE_KEY:latest,GOOGLE_PRIVATE_KEY_ID=GOOGLE_PRIVATE_KEY_ID:latest,FRONTEND_ORIGIN=FRONTEND_ORIGIN:latest,BASE_URL=BASE_URL:latest
      - --set-env-vars=DIALOGFLOW_PROJECT_ID=adg-internal-tech-sandbox,DIALOGFLOW_LOCATION=global,DIALOGFLOW_AGENT_ID=2c676234-651f-4d29-bb48-4d5d041a1b73,DIALOGFLOW_LANGUAGE_CODE=en,AT_USERNAME=MAIN,AT_API_KEY=atsk_f8de7f24254e6968e030cfbe416f62cef40514e283f5276f8b0fa33265d44e11aefb43b7,FLASK_DEBUG=0,VOICE_SAMPLE_RATE_HZ=16000,VOICE_LANGUAGE_CODE=en-US,VOICE_ENABLE_RECORDING=true

images:
  - $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA

substitutions:
  _SERVICE_NAME: customers-talking-api
  _REGION: europe-west1
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
